import React from 'react';
import type { NavKey } from './AppShell';
import { CompanionAssetGallery } from './CompanionAssetGallery';
import { companionAssets } from '../assets/companion-assets';
import { getCurrentAdapterStatuses } from '../domain/adapter-status';

const adapterStatuses = getCurrentAdapterStatuses();

export function AvailabilityView({ kind, onNavigate }: { kind: 'updates' | 'hardware'; onNavigate: (route: NavKey) => void }) {
  const updates = kind === 'updates';
  return <div className="view"><div className="view-heading"><div><p className="eyebrow">{updates ? 'RELEASE CHANNEL' : 'DEVICE DIAGNOSTICS'}</p><h1>{updates ? 'Updates' : 'Hardware'}</h1><p className="muted">{updates ? 'Release information for this offline build.' : 'Local device capabilities and optional surfaces.'}</p></div></div>{updates ? <><section className="list-card" aria-labelledby="updates-status-title" style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) 220px', gap: 24, padding: 24, alignItems: 'center' }}><div><span className="pill amber">Offline mode</span><h2 id="updates-status-title" style={{ font: '500 30px Georgia, serif', margin: '16px 0 8px' }}>No update source configured</h2><p className="muted" style={{ margin: 0, lineHeight: 1.6 }}>This build keeps update checks disabled so the workspace stays fully local. You can continue using the current build without a connection.</p><div style={{ marginTop: 20 }}><button className="outline" onClick={() => onNavigate('settings')}>Open Settings</button></div></div><img src={companionAssets.updates.homeTintDefault.url} alt="Local update artwork" style={{ width: '100%', borderRadius: 12, display: 'block' }} /></section><section className="settings-card" aria-label="Update availability" style={{ marginTop: 15 }}><div className="setting-row"><div><strong>Current build</strong><span>Hibi Study Replica · local build</span></div><b className="pill green">Current</b></div><div className="setting-row"><div><strong>Update service</strong><span>External update checks are disabled in offline mode.</span></div><b className="pill amber">Not configured</b></div></section></> : <><section className="settings-card"><div className="setting-row"><div><strong>Notch / companion surface</strong><span>No compatible hardware integration detected</span></div><b className="pill amber">Unavailable</b></div><div className="setting-row"><div><strong>Diagnostics</strong><span>Use Events to inspect local actions and export a support bundle from Settings.</span></div><button className="outline" onClick={() => onNavigate('instrumentation')}>Open Events</button></div></section><section className="settings-card" aria-labelledby="adapter-status-title" style={{ marginTop: 15 }}><h2 id="adapter-status-title" className="settings-section-title">Adapter status</h2>{adapterStatuses.map((adapter) => <div className="setting-row" key={adapter.id}><div><strong>{adapter.label}</strong><span>{adapter.scope === 'local' ? 'Local capability' : adapter.scope === 'external' ? 'External integration' : 'Hardware integration'}</span></div><b className={`pill ${adapter.status === 'available' ? 'green' : 'amber'}`}>{adapter.status === 'available' ? 'Available' : 'Unavailable'}</b></div>)}</section></>}<CompanionAssetGallery /></div>;
}
