import React from 'react';
import type { StudyData } from '../domain/models';
type Props = { data: StudyData; onEvent: (action: string, detail: string, result?: string) => void; onNavigate: (route: any) => void; onOpenCommands?: () => void };
export function HomeView({ data, onEvent, onNavigate, onOpenCommands }: Props) { const today = '2026-09-07'; const todayBlocks = data.blocks.filter((block) => block.start.startsWith(today)); const current = todayBlocks.find((block) => block.start.includes('T09:00')) ?? todayBlocks[0]; const next = todayBlocks.filter((block) => block !== current).slice(0, 3); const planned = todayBlocks.filter((block) => block.category !== 'break').length; return <div className="home-view">
  <div className="eyebrow">MONDAY · 07 SEPTEMBER 2026 <span className="pill green">LOCAL STUDY MODE</span></div>
  <section className="hero"><div><p className="kicker">YOUR DAY, IN ONE PLACE</p><h1>Make room for<br /><em>what matters.</em></h1><p className="subhead">A calm command centre for tasks, time and attention.</p></div><div className="hero-orbit"><span>09—17</span><small>WORK WINDOW</small></div></section>
  <div className="home-grid"><section className="panel now-panel"><div className="panel-head"><span>NOW</span><button onClick={() => onNavigate('focus')}>Focus →</button></div><h2>{current?.title ?? 'No block scheduled'}</h2><p>{current ? `${current.start.slice(11, 16)} · ${Math.round((new Date(current.end).getTime() - new Date(current.start).getTime()) / 60000)} minutes · ${current.category}` : 'Your day is clear.'}</p><div className="progress"><span style={{ width: `${Math.min(100, planned / Math.max(1, data.tasks.length) * 100)}%` }} /></div><small>{planned} work blocks planned today</small></section>
    <section className="panel health-panel"><div className="panel-head"><span>PLAN HEALTH</span><span className="pill amber">{Math.max(0, data.tasks.length - planned)} REVIEW</span></div><div className="health-stat"><strong>{planned} / {data.tasks.length}</strong><span>work blocks placed today</span></div><button className="text-button" onClick={() => { onEvent('validation', 'Reviewed daily plan', 'needs-review'); onNavigate('week'); }}>Review daily plan →</button></section>
    <section className="panel next-panel"><div className="panel-head"><span>UP NEXT</span><span className="muted">TODAY</span></div>{next.map((block) => <div className="next-row" key={block.id}><b>{block.start.slice(11, 16)}</b><span className={block.category === 'break' ? 'break-label' : undefined}>{block.title}</span></div>)}</section>
  </div>
  <button className="quick-input" aria-label="Open quick capture" onClick={() => { onEvent('command', 'Opened quick capture'); onOpenCommands?.(); }}><span>+</span><span>What needs your attention?</span><kbd>/</kbd></button>
</div>; }
