import React, { useMemo, useState } from 'react';
import { EventRecord } from '../App';
import type { AiAuditEvent } from '../ai/history';

type Props = { events: EventRecord[]; aiHistory?: readonly AiAuditEvent[]; onEvent: (action: string, detail: string, result?: string) => void; onClear?: () => void; onClearAiHistory?: () => void };
export function InstrumentationView({ events, aiHistory = [], onEvent, onClear, onClearAiHistory }: Props) {
  const [filter, setFilter] = useState('');
  const visible = useMemo(() => events.filter((event) => `${event.action} ${event.route} ${event.detail}`.toLowerCase().includes(filter.toLowerCase())), [events, filter]);
  const exportEvents = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(events, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = 'hibi-events.json'; link.click(); URL.revokeObjectURL(url); onEvent('export', 'Exported telemetry JSON', 'pass'); };
  return <div className="view instrumentation-view"><div className="view-heading"><div><p className="eyebrow">LOCAL TELEMETRY · ORDERED EVENTS</p><h1>Instrumentation</h1><p className="muted">{events.length} events · {aiHistory.length} AI audit entries</p></div><div className="heading-actions"><button className="outline" onClick={exportEvents}>Export JSON</button><button className="primary" onClick={() => { if (window.confirm('Limpar o histórico de eventos?')) { onClear?.(); onEvent('clear', 'Cleared event log', 'pass'); } }}>Clear log</button></div></div><div className="telemetry-summary"><div><strong>{events.length}</strong><span>events</span></div><div><strong>{aiHistory.length}</strong><span>AI audit</span></div><div><strong>100%</strong><span>local only</span></div></div><input className="search-input" value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Filter by route, action or summary" /><section className="list-card event-list">{visible.map((event) => <div className="event-row" key={event.id}><span className="event-time">{event.at}</span><span className="event-route">/{event.route}</span><strong>{event.action}</strong><span className="event-detail">{event.detail}</span>{event.result && <span className={`result ${event.result}`}>{event.result}</span>}</div>)}{!visible.length && <p className="empty">No events match this filter.</p>}</section><div className="heading-actions" style={{ marginTop: 32 }}><h2 style={{ margin: 0 }}>AI history</h2><button className="outline" onClick={() => { if (window.confirm('Limpar o histórico de IA?')) { onClearAiHistory?.(); onEvent('clear', 'Cleared AI history', 'pass'); } }}>Clear AI history</button></div><section className="list-card event-list">{aiHistory.map((entry, index) => <div className="event-row" key={`${entry.requestId}-${entry.type}-${index}`}><span className="event-time">{new Date(entry.at).toLocaleString()}</span><span className="event-route">{entry.requestId}</span><strong>{entry.type}</strong><span className="event-detail">{entry.provider ?? 'local'}{entry.model ? ` · ${entry.model}` : ''}{entry.tools?.length ? ` · ${entry.tools.join(', ')}` : ''} · {entry.summary}</span><span className={`result ${entry.type === 'failed' ? 'pending' : ''}`}>{entry.type}</span></div>)}{!aiHistory.length && <p className="empty">No AI history yet.</p>}</section></div>;
}
