import React, { useMemo, useState } from 'react';
import type { Note, StudyData } from '../domain/models';

type Props = { data: StudyData; onCreate: (title: string, content: string) => void; onUpdate: (id: string, changes: Partial<Omit<Note, 'id'>>) => void; onDelete: (id: string) => void };
type Editor = { id?: string; title: string; content: string };

function NoteForm({ editor, onCancel, onSubmit, titleId }: { editor: Editor; onCancel?: () => void; onSubmit: (title: string, content: string) => void; titleId: string }) {
  const [title, setTitle] = useState(editor.title);
  const [content, setContent] = useState(editor.content);
  return <form className="settings-card" aria-label={editor.id ? 'Edit note' : 'Create note'} onSubmit={(event) => { event.preventDefault(); if (title.trim()) onSubmit(title.trim(), content); }}><label htmlFor={titleId}>Title</label><input id={titleId} className="search-input" value={title} onChange={(event) => setTitle(event.target.value)} required /><label htmlFor={`${titleId}-content`}>Content</label><textarea id={`${titleId}-content`} className="search-input" value={content} onChange={(event) => setContent(event.target.value)} rows={5} /><div className="heading-actions"><button className="primary" type="submit">{editor.id ? 'Save note' : 'Add note'}</button>{onCancel && <button className="outline" type="button" onClick={onCancel}>Cancel</button>}</div></form>;
}

export function NotesView({ data, onCreate, onUpdate, onDelete }: Props) {
  const [query, setQuery] = useState(''); const [folder, setFolder] = useState<string | null>(null); const [editor, setEditor] = useState<Editor | null>(null); const [pendingDelete, setPendingDelete] = useState<{ id: string; title: string } | null>(null);
  const notes = useMemo(() => data.notes.filter((note) => (!folder || (note.folder ?? 'Bento') === folder) && `${note.title} ${note.content}`.toLowerCase().includes(query.toLowerCase())), [data.notes, query, folder]);
  return <div className="view"><div className="view-heading"><div><p className="eyebrow">CAPTURE LAYER</p><h1>Notes</h1><p className="muted">{data.notes.length} local notes · searchable</p></div><button className="primary" onClick={() => setEditor({ title: '', content: '' })}>+ New note</button></div><NoteForm editor={{ title: '', content: '' }} titleId="new-note-title" onSubmit={(title, content) => onCreate(title, content)} /><input className="search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search notes" aria-label="Search notes" /><div className="filter-row"><button className={`filter ${folder === null ? 'active' : ''}`} onClick={() => setFolder(null)}>All</button><button className={`filter ${folder === 'Bento' ? 'active' : ''}`} onClick={() => setFolder(folder === 'Bento' ? null : 'Bento')}>Folder · Bento</button></div><section className="list-card">{notes.map((note) => <div className="task-row" key={note.id}><div><strong>{note.title}</strong><span>{note.content || 'Sem conteúdo'} · {note.folder ?? 'Bento'}</span></div><button className="icon-button" aria-label={`Edit ${note.title}`} onClick={() => setEditor({ id: note.id, title: note.title, content: note.content })}>✎</button><button className="icon-button" aria-label={`Delete ${note.title}`} onClick={() => setPendingDelete({ id: note.id, title: note.title })}>×</button></div>)}{!notes.length && <p className="empty">No notes match this search.</p>}</section>{editor?.id && <div className="overlay" onMouseDown={() => setEditor(null)}><section className="palette" role="dialog" aria-modal="true" aria-labelledby="edit-note-title" onMouseDown={(event) => event.stopPropagation()}><h2 id="edit-note-title">Edit note</h2><NoteForm editor={editor} titleId="edit-note-title-input" onCancel={() => setEditor(null)} onSubmit={(title, content) => { onUpdate(editor.id!, { title, content, updatedAt: new Date().toISOString() }); setEditor(null); }} /></section></div>}{pendingDelete && <DeleteConfirmation title={pendingDelete.title} onCancel={() => setPendingDelete(null)} onConfirm={() => { onDelete(pendingDelete.id); setPendingDelete(null); }} />}</div>;
}

function DeleteConfirmation({ title, onCancel, onConfirm }: { title: string; onCancel: () => void; onConfirm: () => void }) { return <div className="overlay"><section className="palette" role="dialog" aria-modal="true" aria-labelledby="delete-confirm-title"><h2 id="delete-confirm-title">Delete {title}?</h2><p>This action cannot be undone.</p><button className="outline" type="button" onClick={onCancel} autoFocus>Cancel</button><button className="primary" type="button" onClick={onConfirm}>Confirm delete</button></section></div>; }
