import React, { useState } from 'react';
import { localNoon, shiftDayKey, todayKey } from '../domain/date-context';
import { durationMinutes, toDateKey } from '../domain/schedule';
import { parseIcsEvents, toIcsCalendar } from '../domain/ics';
import type { ScheduleBlock, StudyData } from '../domain/models';
type Props = { data: StudyData; onEvent: (action: string, detail: string, result?: string) => void; onCreateBlock: (input: Omit<ScheduleBlock, 'id'>) => void; onDeleteBlock?: (id: string) => void };
const names = ['SUN','MON','TUE','WED','THU','FRI','SAT'];
const daysFrom = (key: string) => Array.from({ length: 7 }, (_, i) => shiftDayKey(key, i));
export function WeekView({ data, onEvent, onCreateBlock, onDeleteBlock }: Props) {
  const [layer, setLayer] = useState<'all' | 'schedule' | 'important' | 'wellbeing'>('all');
  const [weekStart, setWeekStart] = useState(() => todayKey());
  const matchesLayer = (block: ScheduleBlock) => layer === 'all' || layer === 'schedule' || (layer === 'important' ? block.isHard === true : block.category === 'break');
  const days = daysFrom(weekStart);
  const add = (date: string, hour: number) => onCreateBlock({ title: 'Quick study block', start: `${date}T${String(hour).padStart(2,'0')}:00:00`, end: `${date}T${String(hour + 1).padStart(2,'0')}:00:00`, category: 'work' });
  const importIcs = async (file: File) => { const events = file.text ? parseIcsEvents(await file.text()) : []; for (const event of events) onCreateBlock({ ...event, category: 'work' }); onEvent('import', file.name, `${events.length} imported`); };
  const exportIcs = () => { const url = URL.createObjectURL(new Blob([toIcsCalendar(data.blocks)], { type:'text/calendar' })); const link = document.createElement('a'); link.href=url; link.download='hibi-calendar.ics'; link.click(); URL.revokeObjectURL(url); onEvent('export','Exported calendar ICS','pass'); };
  const shortDay = (date: string) => { const day = names[localNoon(date).getDay()]; return `${day[0]}${day.slice(1).toLowerCase()} ${date.slice(8, 10)}`; };
  const rangeLabel = `${shortDay(days[0])} — ${shortDay(days[6])}`;
  const monthLabel = localNoon(weekStart).toLocaleDateString('en-GB', { month: 'long', year: 'numeric' }).toUpperCase();
  const quickAdd = (date: string, hour: number) => add(date, hour);
 return <div className="view calendar-view"><div className="view-heading"><div><p className="eyebrow">WEEKLY PLAN · {monthLabel}</p><h1>Week · {rangeLabel}</h1><p className="muted">Work windows, protected time and recurring reminders</p></div><div className="heading-actions"><button className="outline" aria-label="Previous week" onClick={() => { setWeekStart(shiftDayKey(weekStart,-7)); onEvent('navigation', 'Previous week'); }}>←</button><button className="outline" aria-label="Next week" onClick={() => { setWeekStart(shiftDayKey(weekStart,7)); onEvent('navigation', 'Next week'); }}>→</button><label className="outline">Import .ics<input hidden type="file" accept=".ics,text/calendar" onChange={(e) => { const f=e.target.files?.[0]; if(f) void importIcs(f); }} /></label><button className="outline" onClick={exportIcs}>Export .ics</button><button className="primary" onClick={() => add(weekStart,8)}>+ Add</button></div></div><div className="calendar-toolbar">{([['all','All layers'],['schedule','Schedule'],['important','Important'],['wellbeing','Wellbeing']] as const).map(([value, label]) => <button key={value} className={`filter ${layer === value ? 'active' : ''}`} onClick={() => { setLayer(value); onEvent('filter', `Week · ${label}`); }}>{label}</button>)}</div><div className="week-grid"><div className="week-corner">TIME</div>{days.map((date) => <div className="day-head" key={date}>{names[localNoon(date).getDay()]}<b>{date.slice(8,10)}</b></div>)}{Array.from({length:15},(_,i)=>i+8).map((hour) => <React.Fragment key={hour}><div className="time-label">{hour}:00</div>{days.map((date) => { const blocks=data.blocks.filter((b)=>toDateKey(b.start)===date && Number(b.start.slice(11,13))===hour && matchesLayer(b)); return <div className="week-slot" key={`${date}-${hour}`} role="button" tabIndex={0} aria-label={`Add block ${date} at ${String(hour).padStart(2, '0')}:00`} onClick={() => quickAdd(date,hour)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); quickAdd(date,hour); } }}>{blocks.map((block) => <button className="mini-card orange" aria-label={`Delete ${block.title} at ${block.start.slice(11, 16)} on ${date}`} key={block.id} onClick={(event) => { event.stopPropagation(); onDeleteBlock?.(block.id); }}>{block.title}<span>{durationMinutes(block)/60}h · ×</span></button>)}</div>; })}</React.Fragment>)}</div></div>;
}
