import React from 'react';
import { durationMinutes, toDateKey } from '../domain/schedule';
import type { ScheduleBlock, StudyData } from '../domain/models';
type Props = { data: StudyData; onEvent: (action: string, detail: string, result?: string) => void; onCreateBlock: (input: Omit<ScheduleBlock, 'id'>) => void; onDeleteBlock?: (id: string) => void };
const START = '2026-09-07'; const OFFSET = '-03:00'; const names = ['SUN','MON','TUE','WED','THU','FRI','SAT'];
const daysFrom = (key: string) => Array.from({ length: 7 }, (_, i) => { const d = new Date(`${key}T12:00:00${OFFSET}`); d.setDate(d.getDate() + i); return d.toISOString().slice(0, 10); });
const icsDate = (value: string) => `${value.slice(0,4)}-${value.slice(4,6)}-${value.slice(6,8)}T${value.slice(9,11)}:${value.slice(11,13)}:00${OFFSET}`;
export function WeekView({ data, onEvent, onCreateBlock, onDeleteBlock }: Props) {
  const days = daysFrom(START);
  const add = (date: string, hour: number) => onCreateBlock({ title: 'Quick study block', start: `${date}T${String(hour).padStart(2,'0')}:00:00${OFFSET}`, end: `${date}T${String(hour + 1).padStart(2,'0')}:00:00${OFFSET}`, category: 'work' });
  const importIcs = async (file: File) => { let count = 0; for (const match of file.text ? [...(await file.text()).matchAll(/BEGIN:VEVENT([\s\S]*?)END:VEVENT/g)] : []) { const body = match[1]; const start = body.match(/DTSTART(?:;[^:]+)?:([0-9]{8}T[0-9]{6})/)?.[1]; const end = body.match(/DTEND(?:;[^:]+)?:([0-9]{8}T[0-9]{6})/)?.[1]; const title = body.match(/SUMMARY:(.*)/)?.[1]?.trim() || 'Imported event'; if (start && end) { onCreateBlock({ title, start: icsDate(start), end: icsDate(end), category: 'work' }); count++; } } onEvent('import', file.name, `${count} imported`); };
  const exportIcs = () => { const esc = (v: string) => v.replace(/[\\;,]/g, '\\$&').replace(/\n/g, '\\n'); const events = data.blocks.map((b) => `BEGIN:VEVENT\nUID:${b.id}@hibi\nDTSTART:${b.start.replace(/[-:]/g,'').replace('.000','')}\nDTEND:${b.end.replace(/[-:]/g,'').replace('.000','')}\nSUMMARY:${esc(b.title)}\nEND:VEVENT`).join('\n'); const url = URL.createObjectURL(new Blob([`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Hibi//EN\n${events}\nEND:VCALENDAR`], { type:'text/calendar' })); const link = document.createElement('a'); link.href=url; link.download='hibi-calendar.ics'; link.click(); URL.revokeObjectURL(url); onEvent('export','Exported calendar ICS','pass'); };
  return <div className="view calendar-view"><div className="view-heading"><div><p className="eyebrow">WEEKLY PLAN · SEPTEMBER 2026</p><h1>Mon 07 — Sun 13</h1><p className="muted">Work windows, protected time and recurring reminders</p></div><div className="heading-actions"><label className="outline">Import .ics<input hidden type="file" accept=".ics,text/calendar" onChange={(e) => { const f=e.target.files?.[0]; if(f) void importIcs(f); }} /></label><button className="outline" onClick={exportIcs}>Export .ics</button><button className="primary" onClick={() => add(START,8)}>+ Add</button></div></div><div className="calendar-toolbar"><button className="filter active">All layers</button><button className="filter">Schedule</button><button className="filter">Important</button><button className="filter">Wellbeing</button></div><div className="week-grid"><div className="week-corner">TIME</div>{days.map((date) => <div className="day-head" key={date}>{names[new Date(`${date}T12:00:00${OFFSET}`).getDay()]}<b>{date.slice(8,10)}</b></div>)}{Array.from({length:15},(_,i)=>i+8).map((hour) => <React.Fragment key={hour}><div className="time-label">{hour}:00</div>{days.map((date) => { const block=data.blocks.find((b)=>toDateKey(b.start)===date && Number(b.start.slice(11,13))===hour); return <div className="week-slot" key={`${date}-${hour}`} onClick={() => add(date,hour)}>{block && <button className="mini-card orange" aria-label={`Delete ${block.title}`} onClick={(event) => { event.stopPropagation(); onDeleteBlock?.(block.id); }}>{block.title}<span>{durationMinutes(block)/60}h · ×</span></button>}</div>; })}</React.Fragment>)}</div><div className="conflict-inline"><span>✓</span><strong>No hard conflicts detected</strong><span className="muted">Protected lunch, walking and classes are respected.</span></div></div>;
}
