import { useState, type FormEvent } from 'react';
import { Check, Flame, Pencil, Plus, Trash2 } from 'lucide-react';
import type { Habit, StudyData } from '../../../domain/models';
import { todayKey } from '../../../domain/date-context';
import { progressFor, streakFor } from '../../progress-rhythm';
import { HibiEmptyState } from '../components/HibiEmptyState';
import { ActionDialog } from '../components/ActionDialog';
import { HibiUiRoot } from '../components/HibiUiRoot';
import { SectionHeader } from '../components/SectionHeader';
import { useT } from '../../../i18n/LocaleProvider';
import './rhythm-screens.css';

type Changes = Partial<Omit<Habit, 'id'>>;
type Props = Readonly<{ data: StudyData; onCreate: (title: string, frequency?: Habit['frequency'], targetPerWeek?: number) => void; onToggleCompletion: (id: string, date: string, completed: boolean) => void; onUpdate: (id: string, changes: Changes) => void; onDelete: (id: string) => void; now?: Date }>;

export function HabitsScreen({ data, onCreate, onToggleCompletion, onUpdate, onDelete, now }: Props) {
  const t = useT();
  const today = todayKey(now);
  const [title, setTitle] = useState('');
  const [frequency, setFrequency] = useState<Habit['frequency']>('daily');
  const [target, setTarget] = useState('3');
  const [editing, setEditing] = useState<string | null>(null);
  const [draft, setDraft] = useState<{ title: string; frequency: Habit['frequency']; target: string }>({ title: '', frequency: 'daily', target: '3' });
  const [deleting, setDeleting] = useState<Habit | null>(null);
  const submit = (event: FormEvent) => { event.preventDefault(); const clean = title.trim(); const value = frequency === 'daily' ? 7 : Number(target); if (clean && Number.isFinite(value) && value > 0) { onCreate(clean, frequency, value); setTitle(''); } };
  const save = (event: FormEvent, habit: Habit) => { event.preventDefault(); const clean = draft.title.trim(); const value = draft.frequency === 'daily' ? 7 : Number(draft.target); if (!clean || !Number.isFinite(value) || value <= 0) return; const changes: Changes = { title: clean, frequency: draft.frequency }; if (draft.frequency === 'weekly') changes.targetPerWeek = value; onUpdate(habit.id, changes); setEditing(null); };
  const completed = data.habits.filter((habit) => habit.completedDates.includes(today)).length;
  const streak = Math.max(0, ...data.habits.map((habit) => streakFor(habit, today)));
  return <HibiUiRoot className="rhythm-screen habits-screen">
    <SectionHeader title={t('habits.title')} subtitle={`${data.habits.length} hábitos · pequenos passos que se repetem`} actions={<button className="rhythm-button rhythm-button--primary" type="button" onClick={() => document.getElementById('new-habit-title')?.focus()}><Plus size={16} aria-hidden="true" />{t('habits.new')}</button>} />
    <div className="rhythm-stats"><div><span>Hoje</span><strong>{completed} <small>de {data.habits.length}</small></strong></div><div><span>Sequência mais longa</span><strong><Flame size={17} aria-hidden="true" />{streak} <small>dias</small></strong></div><div><span>Pendentes</span><strong>{Math.max(0, data.habits.length - completed)}</strong></div></div>
    <form className="rhythm-create" aria-label="Criar hábito" onSubmit={submit}><div><label htmlFor="new-habit-title">Nome do hábito</label><input id="new-habit-title" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: Ler por 20 minutos" required /></div><div><label htmlFor="new-habit-frequency">Frequência</label><select id="new-habit-frequency" value={frequency} onChange={(event) => setFrequency(event.target.value as Habit['frequency'])}><option value="daily">Todos os dias</option><option value="weekly">Toda semana</option></select></div>{frequency === 'weekly' && <div><label htmlFor="new-habit-target">Vezes por semana</label><input id="new-habit-target" type="number" min="1" step="1" value={target} onChange={(event) => setTarget(event.target.value)} /></div>}<button className="rhythm-button rhythm-button--primary" type="submit">Adicionar</button></form>
    <section className="rhythm-list" aria-label="Hábitos"><header><div><h2>Seu ritmo</h2><p>Marque o que foi feito hoje; o histórico permanece local.</p></div><span>{today}</span></header>{data.habits.length === 0 ? <HibiEmptyState icon={Flame} tone="mint" title="Nenhum hábito ainda" description="Comece com uma ação pequena e repetível." /> : <div className="rhythm-items">{data.habits.map((habit) => { const done = habit.completedDates.includes(today); const progress = progressFor(habit, today); const percent = Math.min(100, Math.round(progress.completed / Math.max(progress.target, 1) * 100)); return <article className="rhythm-item" key={habit.id}><button className={`rhythm-check ${done ? 'is-checked' : ''}`} aria-label={`${done ? 'Desmarcar' : 'Marcar'} ${habit.title} hoje`} onClick={() => onToggleCompletion(habit.id, today, !done)}>{done && <Check size={15} aria-hidden="true" />}</button>{editing === habit.id ? <form className="rhythm-edit" aria-label={`Editar ${habit.title}`} onSubmit={(event) => save(event, habit)}><input aria-label={`Nome de ${habit.title}`} value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} required /><select value={draft.frequency} onChange={(event) => setDraft({ ...draft, frequency: event.target.value as Habit['frequency'] })}><option value="daily">Todos os dias</option><option value="weekly">Toda semana</option></select>{draft.frequency === 'weekly' && <input aria-label={`Meta de ${habit.title}`} type="number" min="1" value={draft.target} onChange={(event) => setDraft({ ...draft, target: event.target.value })} />}<button className="rhythm-button rhythm-button--primary" type="submit">Salvar</button><button className="rhythm-button" type="button" onClick={() => setEditing(null)}>Cancelar</button></form> : <div className="rhythm-item__copy"><strong>{habit.title}</strong><span>{habit.frequency === 'daily' ? 'Diário' : `${habit.targetPerWeek} vezes por semana`} · sequência de {streakFor(habit, today)} dias</span><div className="rhythm-progress"><span style={{ width: `${percent}%` }} /></div></div>}<div className="rhythm-item__actions"><button aria-label={`Editar ${habit.title}`} onClick={() => { setEditing(habit.id); setDraft({ title: habit.title, frequency: habit.frequency, target: String(habit.targetPerWeek) }); }}><Pencil size={15} aria-hidden="true" /></button><button aria-label={`Excluir ${habit.title}`} onClick={() => setDeleting(habit)}><Trash2 size={15} aria-hidden="true" /></button></div></article>; })}</div>}</section>
    {deleting && <ActionDialog trigger={<button className="sr-only" aria-hidden="true" type="button">Excluir hábito</button>} isOpen onOpenChange={(open) => !open && setDeleting(null)} title={`Excluir ${deleting.title}?`} description="O histórico desse hábito também será removido."><div className="rhythm-dialog__actions"><button className="rhythm-button" onClick={() => setDeleting(null)}>Cancelar</button><button className="rhythm-button rhythm-button--danger" onClick={() => { onDelete(deleting.id); setDeleting(null); }}>Excluir hábito</button></div></ActionDialog>}
  </HibiUiRoot>;
}
